### PR TITLE
Replaced setup.py with setup.cfg.

### PR DESCRIPTION
**Pull request by KOLANICH**
Added pyproject.toml.
Fetching version from git tags since now.

### CODE REVIEW

**Comment by k4yt3x** [comment]
What are the benefits of this change?
I feel like the setup.py works fine.

**Comment by KOLANICH** [comment]
`setup.cfg` is a declarative and **data**. `setup.py` is **code** in a Turing-complete language that cannot be reliably parsed without code execution and edited automatically. It is also easier to read for humans.

**Comment by k4yt3x** [comment]
Hmmm that sounds like a valid point. Let me just look some documentations up before getting back to this.

**Comment by FelixSchwarz** [comment]
I'd like to support moving parameters into `setup.cfg` instead of `setup.py`. However removing `setup.py` entirely means (IIRC) that you need a quite recent version of `setuptools`. For example RHEL 8 ships `setuptools` version 39.2. I'm not 100% sure but I think if you leave a bare-bones `setup.py` with just the `setup()` that means also older `setuptools` version can use the parameters from `setup.py`.

**Comment by KOLANICH** [comment]
>I'm not 100% sure but I think if you leave a bare-bones setup.py with just the setup() that means also older setuptools version can use the parameters from setup.py.

You are correct. But I see no reason to do that, instead I just install the latest versions of the tools (yes, with `sudo` :). I wonder which of the solutions the maintainer of this repo prefers.

**Comment by FelixSchwarz** [comment]
> But I see no reason to do that, instead I just install the latest versions of the tools (yes, with sudo :).

Requiring very recent versions makes it much harder to package stuff for distros. Installing packages with sudo inside the system's Python directory manually is very likely to cause a lot of breakage. I'm also the [certbot](https://github.com/certbot/certbot) maintainers for Fedora and Fedora EPEL (RHEL, CentOS, ...) and about 50% of the bug reports I'm seeing are from users who installed incompatible stuff inside their system Python directory.

Anyway: A distro maintainer can probably also patch the setup.cfg/setup.py if necessary so this might not be a deal breaker but it will make packaging much harder.  However I have a pretty strong opinion on `sudo pip …` :-)

**Comment by KOLANICH** [comment]
OK, restored `setup.py`.

**Comment by k4yt3x** [comment]
What are the final conclusions then, should we switch?

**Review by k4yt3x — APPROVED** [review]

**Pull request merged**
