### PR TITLE
Added the .editorconfig according to PEP 8

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by k4yt3x** [comment]
Not a necessary ingredient. This is up to the editor and some personal preference.
I don't see a point including it in the repo.

**Comment by KOLANICH** [comment]
It seems you deeply misunderstand what `.editorconfig` is.

>>This is up to the editor

.editorconfig was designed to be cross-editor.

>and some personal preference.

All projects enforce personal preferences of their authors. Especially in python, which disallows mixing tabs and spaces. I.e. if someone sends you a PR when the changed lines use tabs instead of spaces, then it is likely that
1. that code won't even work, python enforces consistency;
2. even if it worked, you will still demand replacing tabs with spaces.

The contributor will say then: "But my editor configured to use tabs, I won't change my editor preferences only because your project uses spaces".

.editorconfig files do that for him.

**Comment by k4yt3x** [comment]
> .editorconfig was designed to be cross-editor.

Yeah I didn't look that up. Sorry I'm trying to stay awake right now after a night without sleep.

This repository strictly requires all code to be formatted with Black formatter. I don't think it'll make any differences?

**Comment by KOLANICH** [comment]
It makes editing more convenient.

**Comment by k4yt3x** [comment]
Perhaps, I've never needed it.
It still doesn't make sense to me to have this extra file in the repository. It looks redundant to me.

**Pull request closed without merging**
